use_frameworks!

platform :ios, '9.0'

target 'zjLogin_Example' do
  pod 'zjLogin', :path => '../'
  pod 'zjNetWork', :path =>'../../zjNetWork'

  target 'zjLogin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
